### Numpy Operations

In [1]:
import numpy as np

**Boolean indexing in numpy**

In [2]:
arr = np.array([1, 2, 3, 4, 5])

In [17]:
bool_idx = arr >= 2

In [18]:
bool_idx # Output: [False False  True  True  True]

array([False,  True,  True,  True,  True])

In [19]:
print(arr[bool_idx])

[2 3 4 5]


**Using Pure Python**

In [6]:
l = [1,2,3,4,5]
o = [each>2 for each in l]

In [7]:
o

[False, False, True, True, True]

In [23]:
arr_c = np.array([10, 0, 12, 14, -3])

In [24]:
b = [False, False, True, True, True]

In [25]:
arr_c[b]

array([12, 14, -3])

In [21]:
l = np.array([1,2,3,45,6])

In [22]:
l[[False, True, False, False, False]]

array([2])

**Mean Using Numpy**

In [26]:
arr = np.array([2, 4, 6, 8, 10])
mean_value = np.mean(arr)
print(mean_value)

6.0


**Median Using Numpy**

- For meadian list must be sorted. Numpy median sorts the list automatically.
- If the dataset is in odd form it gets the middle value
- If the dataset is in even format it get two consecutive middle value sums it up and gives average as median of the dataset.

In [30]:
arr = np.array([2, 16, 8, 10, 12])
# 2, 4, 8, 10, 12, 16
median_value = np.median(arr)
print(median_value)

10.0


**Using Pure Python**

In [ ]:
l = [10, 12, 32, 45, 66, 99, 122, 133, 145]

In [ ]:
1. Count the total number is array count
2. Check if it is even or odd
3. 

In [61]:
a = [1,2,3,4,5,6,7,8]
 #0 1 2 3 4 5 6 7

In [62]:
if len(a) % 2 == 0:
    m = int(len(a)/2)
    meadian = (a[m-1] + a[m])/2
else:
    m = int(len(a)/2)
    meadian = a[m]

In [63]:
meadian

4.5

In [74]:
la = np.arange(10000, 1234567890)

In [75]:
m = int(len(la)/2)

In [76]:
meadian = (la[m-1] + la[m])/2

In [78]:
meadian

617288944.5

In [79]:
meadian_numpy = np.median(la)

In [80]:
meadian_numpy

617288944.5

**Mod**

In [97]:
arr = [1,3,3,3,2,2,5,7]

In [98]:
arr

[1, 3, 3, 3, 2, 2, 5, 7]

In [99]:
from scipy import stats

In [100]:
stats.mode(arr)

ModeResult(mode=3, count=3)

**Get all the mode using**

In [107]:
l = [1, 3, 3, 3, 2, 2, 2, 4, 4, 4, 5, 7]


In [108]:
l

[1, 3, 3, 3, 2, 2, 2, 4, 4, 4, 5, 7]

In [112]:
d = {}
for each in l:
    if each in d:
        d[each] = d[each] + 1
    else:
        d[each] = 1

In [113]:
d

{1: 1, 3: 3, 2: 3, 4: 3, 5: 1, 7: 1}

In [126]:
largest = 1
for k, v in d.items():
    if v > 1:
        largest = v
        
all_modes = []
for k, v in d.items():
    if v == largest:
        all_modes.append(k)

In [127]:
largest

3

In [128]:
all_modes

[3, 2, 4]

In [139]:
print(f"All modes are: {sorted(all_modes)}, count: {largest}")

All modes are: [2, 3, 4], count: 3


**Other numpy func**

In [101]:
arr = np.array([1, 2, 3])
print(arr + 10)  # Output: [11 12 13]

[11 12 13]


In [103]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [104]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
print(np.sum(arr))  # Output: 21
print(np.sum(arr, axis=0))  # Output: [5 7 9]
print(np.sum(arr, axis=1))  # Output: [ 6 15]

21
[5 7 9]
[ 6 15]


In [106]:
print(np.min(arr))  # Output: 1
print(np.max(arr, axis=0))  # Output: [4 5 6]

1
[4 5 6]
