### Numpy

**Pip Installation command for numpy library**

To install latest version

pip install numpy

To install vewrsion specific

pip install numpy==1.26.1

**To import numpy module**

In [6]:
import numpy as np

In [17]:
# Create a 1D array
arr = numpy.array([1, 2, 3, 4])

In [25]:
# Get the length of array
len(arr)

4

In [20]:
# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

In [21]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [26]:
# Create an array of zeros aka null array

# Here 1 is row and 2 is column. This is also know as shape of array
zeros = np.zeros((1, 2))
print(zeros)

[[0. 0.]]


In [ ]:
# Linespace is used to equally split the number between 1 and last input
# By default it will have 50 equal splits

In [35]:
np.linspace(0, 1, 4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [75]:
arr = np.linspace(0, 1)

In [76]:
arr

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [80]:
op = []

#### Get diff of successor values from list

In [81]:
for i in range(len(arr)-1):
    diff = arr[i+1] - arr[i]
    op.append(diff)

In [108]:
list(set(op))

[0.020408163265306145,
 0.02040816326530613,
 0.020408163265306117,
 0.02040816326530609,
 0.020408163265306034,
 0.02040816326530612,
 0.020408163265306124]

In [44]:
arr[5] - arr[4]

0.020408163265306117

In [112]:
# Create an array of ones
ones = np.ones((3, 2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [115]:
#Basic Array Operations
arr2d = np.array([[12, 321, 234], [39, 15, 63]])

In [116]:
arr2d

array([[ 12, 321, 234],
       [ 39,  15,  63]])

In [121]:
# Indexing
print(arr2d[0, 1])  # Element at the first row and second column

321


In [122]:
# Slicing
print(arr2d[:, 1])  # Second column
print(arr2d[1, :])  # Second row

[321  15]
[39 15 63]


In [1]:
# Math

In [123]:
# Element-wise operations
arr = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [124]:
arr

array([1, 2, 3])

In [125]:
arr2

array([4, 5, 6])

In [132]:
# Addition
print(arr + arr2)

[5 7 9]


In [138]:
1.73*1.73

2.9929

In [133]:
# Element-wise operations
arr = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
print(arr + arr2)

# Multiplication
print(arr * arr2)

# Universal functions (ufuncs)
print(np.sqrt(arr2))  # Square root of each element


[5 7 9]
[ 4 10 18]
[2.         2.23606798 2.44948974]


In [139]:
#random number
# Random numbers between 0 and 1
random_array = np.random.rand(3, 2)
print(random_array)

[[0.61887245 0.86162659]
 [0.9131281  0.1751822 ]
 [0.6268963  0.42813964]]


In [141]:
# Random integers
random_ints = np.random.randint(0, 100000, size=(8, 12))
print(random_ints)


[[58419 74926 34275 56728 97765 33082  3317  4334 21976 82083 41571 17562]
 [77470 66066 81263 14206 31405 96519 54635 24874 16560 42829 53280 66931]
 [26469 60339 39096 17427 45065 94015 38653 92760 97086 31014 16714 51941]
 [50724  7000  1351 86812  2003 49125  8374 77222 75956 54504 76429 37014]
 [ 9995 39316 70663 21045 49014 92178 56179 55223 68798 85702 76303  5458]
 [78288 12300 26197 75796 92519 92680 58326  1717 42783 88476 73169 12330]
 [31941  5538 76662 98981 77986 26254 61108 74329 53963 69595 85322 51211]
 [89019 12275 78069 13893 47362 93030 32853 97095 37211 95008 31211 16891]]


In [187]:
# Array with arange
arr = np.arange(100000, 1000000)

In [188]:
# Reshape the array
reshaped_arr = arr.reshape(3000, 300)

In [189]:
arr

array([100000, 100001, 100002, ..., 999997, 999998, 999999])

In [190]:
reshaped_arr

array([[100000, 100001, 100002, ..., 100297, 100298, 100299],
       [100300, 100301, 100302, ..., 100597, 100598, 100599],
       [100600, 100601, 100602, ..., 100897, 100898, 100899],
       ...,
       [999100, 999101, 999102, ..., 999397, 999398, 999399],
       [999400, 999401, 999402, ..., 999697, 999698, 999699],
       [999700, 999701, 999702, ..., 999997, 999998, 999999]])

In [192]:
from datetime import datetime

In [197]:
datetime.now()

datetime.datetime(2024, 8, 30, 11, 44, 13, 18381)

In [198]:
start = datetime.now()
# Using Loop
flatten_using_loop_arr = []
for each in reshaped_arr:
    flatten_using_loop_arr.extend(each)
end = datetime.now()
print(f"time taken: {end-start}")

time taken: 0:00:00.033732


In [185]:
flatten_using_loop_arr

[4, 9, 14, 19, 24, 29, 34, 39, 44, 49]

In [199]:
# Flatten the matrix using numpy
start = datetime.now()
flatten_using_numpy_arr = reshaped_arr.flatten()
end = datetime.now()
print(f"time taken: {end-start}")

time taken: 0:00:00.004024
